# Generated by Django 4.2 on 2023-04-07 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=30)),
            ],
            options={
                'verbose_name': 'purchase',
                'verbose_name_plural': 'purchases',
                'db_table': 'purchases',
                'default_related_name': 'purchases',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation', models.DecimalField(decimal_places=2, max_digits=31)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.purchase')),
            ],
            options={
                'verbose_name': 'detail',
                'verbose_name_plural': 'details',
                'db_table': 'details',
                'default_related_name': 'details',
            },
        ),
    ]
